[package]
name = "jfi_lib"
version = "0.1.3"
edition = "2021"
authors = ["github.com/jerryshell"]

[dependencies]
reqwest = { version = "0.11.10", default-features = false, features = [
    "rustls-tls",
] }
tokio = { version = "1.18.2", features = ["full"] }
tokio-test = "0.4.2"
anyhow = "1.0.57"
serde = "1.0.137"
serde_json = "1.0.81"
serde_derive = "1.0.137"
cached = "0.34.0"
