[package]
name = "jfi_lib"
version = "0.1.3"
edition = "2021"
authors = ["github.com/jerryshell"]

[dependencies]
reqwest = { version = "0.11.11", default-features = false, features = [
    "rustls-tls",
] }
tokio = { version = "1.19.2", features = ["full"] }
tokio-test = "0.4.2"
anyhow = "1.0.58"
serde = "1.0.138"
serde_json = "1.0.82"
serde_derive = "1.0.138"
cached = "0.34.1"
