[package]
name = "jfi_http_api"
version = "0.1.2"
edition = "2021"
authors = ["github.com/jerryshell"]

[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
axum = "0.4.8"
jfi_lib = { path = "../jfi_lib" }
serde_json = "1.0.79"
tower-http = { version = "0.2.5", features = ["cors"] }
cached = "0.34.0"
