[package]
name = "jfi_http_api"
version = "0.1.0"
edition = "2021"
authors = ["github.com/jerryshell"]

[dependencies]
tokio = { version = "1.16.1", features = ["full"] }
axum = "0.4.5"
jfi_lib = { path = "../jfi_lib" }
serde_json = "1.0.78"
tower-http = { version = "0.2.2", features = ["cors"] }
