[package]
name = "jfi_http_api"
version = "0.1.3"
edition = "2021"
authors = ["github.com/jerryshell"]

[dependencies]
tokio = { version = "1.18.2", features = ["full"] }
axum = "0.5.6"
jfi_lib = { path = "../jfi_lib" }
serde_json = "1.0.81"
tower-http = { version = "0.3.3", features = ["cors"] }
cached = "0.34.0"
